Algoritmo "Cronometro Laço de repetição"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson costa Santos
// Descrição   : Laços de repetição
// Autor(a)    : Eliana Almeida Nunes Da Silva
// Data atual  : 04/04/2024
Var
// Seção de Declarações das variáveis
 segundos: inteiro

Inicio
   Para segundos <- 59 Ate 0 Passo -1 Faca
      Escreva(segundos)
      Timer(111)
   FimPara

   Escreval("Tempo esgotado!")
Fimalgoritmo